# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TomorrowNews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Moya'
pod 'ObjectMapper'
pod 'PageMenu'
pod 'IQKeyboardManager'
pod 'LeoDanmakuKit', '~> 1.0.1'
pod 'LLSwitch'
  # Pods for TomorrowNews

end
